### ISSUE TITLE
Test is failing

### ISSUE THREAD

**Issue by tomgutz** [dannycoates/zkjs#2]
Hi, I ran the test.js. However I think it didn't do what it is suppose to do. Need some help figuring out went wrong. Below is the console log after running "node test"

connecting [ 'localhost', '2181' ]
connected localhost:2181
draining 1 messages
connected
BADARGUMENTS
does not exist
NONODE
NONODE
NONODE
BADARGUMENTS
does not exist
client end
client closed. with error false
receiver ended queue []

Not sure why it has a BAD ARGUMENTS error since i verified the API and it seems correct.
Thanks.

**Comment by dannycoates** [comment]
What version of ZooKeeper are you running this against?

**Comment by tomgutz** [comment]
Hi, it is zookeeper-3.3.6

**Comment by dannycoates** [comment]
I'm not able to reproduce with 3.3.6. Are you using ACL's or SASL in your ZooKeeper deployment?

I did just push a new version (3.4.0beta5) to npm that fixed some other bugs, could you try that version and tell me if it's still broken?

**Comment by tomgutz** [comment]
No we dont use ACL. My config is more of out-of-the-box. I didnt do any configuration after downloading it. I can confirm that my zookeeper is running since i can use the client that comes with it by running it in CLI.

I have a windows OS environment, just in case it matters.

I also tried the {"version": "3.4.0beta3"} as you suggested. But running the test.js still shows the same errors. It is quite puzzling why it does not work.

**Comment by tomgutz** [comment]
btw is it possible to get the link of where you got your zookeeper and any spcefic details about it? I just wanted to get the same environment you are working on. thanks.

**Comment by tomgutz** [comment]
Dude, I tested it under ubuntu. And it works perfectly. I believe you have a machine other than Windows that is why it works. Correct me if im wrong. 

However, when i run on windows I do see it that it connects to the zookeeper server but it just fails to do stuff when its connect (create, delete, etc...). In particular when  you try to check a node/dir that you created it will spit out the error that node does not exists. And for  creating a node/dir, error says that the code supplied a bad arguments. Which does not make sense since it is correct.

I prefer using your tool rather than the node-zookeeper project since that once has too many dependency. So can you help me debug on this? Any pointers where should I look at?

**Comment by dannycoates** [comment]
I'm mac/linux setup. I don't have easy access to a Windows machine, but I can probably scrounge one up somehow. In the meantime I'd like to write a patch that will give verbose logging at the TCP level that you can run and send me the output, if that sounds good to you?

**Comment by tomgutz** [comment]
Yes this sounds good. Ill run it under 64 and 32 bit systems just in case it matters. Send it as soon as you have it.
Thanks.

**Comment by dannycoates** [comment]
I know it's been forever, but zkjs should be working on Windows as of version 3.4.0

**Comment by tomgutz** [comment]
I tried to run it under windows. And I got this error.

C:\tools\zkjs>node test
connecting [ 'localhost', '2181' ]
connected localhost:2181

C:\tools\zkjs\node_modules\readable-stream\lib_stream_readable.js:816
      ret = Buffer.concat(list, length);
                   ^
TypeError: Object function Buffer(subject, encoding, offset) {
  if (!(this instanceof Buffer)) {
    return new Buffer(subject, encoding, offset);
  }

  var type;

  // Are we slicing?
  if (typeof offset === 'number') {
    this.length = coerce(encoding);
    this.parent = subject;
    this.offset = offset;
  } else {
    // Find the length
    switch (type = typeof subject) {
      case 'number':
        this.length = coerce(subject);
        break;

```
  case 'string':
    this.length = Buffer.byteLength(subject, encoding);
    break;

  case 'object': // Assume object is an array
    this.length = coerce(subject.length);
    break;

  default:
    throw new Error('First argument needs to be a number, ' +
                    'array or string.');
}

if (this.length > Buffer.poolSize) {
  // Big buffer, just alloc one.
  this.parent = new SlowBuffer(this.length);
  this.offset = 0;

} else {
  // Small buffer.
  if (!pool || pool.length - pool.used < this.length) allocPool();
  this.parent = pool;
  this.offset = pool.used;
  pool.used += this.length;
}

// Treat array-ish objects as a byte array.
if (isArrayIsh(subject)) {
  for (var i = 0; i < this.length; i++) {
    this.parent[i + this.offset] = subject[i];
  }
} else if (type == 'string') {
  // We are a string
  this.length = this.write(subject, 0, encoding);
}
```

  }

  SlowBuffer.makeFastBuffer(this.parent, this, this.offset, this.length);
} has no method 'concat'
    at fromList (C:\tools\zkjs\node_modules\readable-stream\lib_stream_readable.js:816:20)
    at Readable.read (C:\tools\zkjs\node_modules\readable-stream\lib_stream_readable.js:308:11)
    at Body.read (C:\tools\zkjs\state.js:23:21)
    at Receiver.read (C:\tools\zkjs\receiver.js:64:21)
    at Receiver.streamReadable (C:\tools\zkjs\receiver.js:112:8)
    at Readable.emit (events.js:64:17)
    at emitReadable_ (C:\tools\zkjs\node_modules\readable-stream\lib_stream_readable.js:385:10)
    at emitReadable (C:\tools\zkjs\node_modules\readable-stream\lib_stream_readable.js:380:5)
    at readableAddChunk (C:\tools\zkjs\node_modules\readable-stream\lib_stream_readable.js:145:7)
    at Readable.push (C:\tools\zkjs\node_modules\readable-stream\lib_stream_readable.js:115:10)
