### ISSUE TITLE
Docs issue (constants accessible on session, not on module export)

### ISSUE THREAD

**Issue by karlbohlmark** [dannycoates/zkjs#5]
Hi, thanks for writing a pure js zookeeper client.

It seems the docs are not up to date when it comes to access to constants like error codes.

```
retryOn: ZK.errors.RETRY_DEFAULTS
```

is not valid, since the `errors`  property resides on the session and not on the module.

I'd say it'd be better to actually have them available directly on the module like in the docs though. What's your thoughts?

**Comment by dannycoates** [comment]
Yes, this is a bug. I'll fix this soon. Thanks!

**Comment by dannycoates** [comment]
Soon is a relative term :/
This is fixed in 3.4.0 on npm
